# Generated by Django 4.0.4 on 2022-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0002_alter_main_page_pic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='potraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='blog_image')),
                ('image2', models.ImageField(upload_to='blog_image')),
                ('image3', models.ImageField(upload_to='blog_image')),
                ('image4', models.ImageField(upload_to='blog_image')),
                ('image5', models.ImageField(upload_to='blog_image')),
                ('image6', models.ImageField(upload_to='blog_image')),
                ('image7', models.ImageField(upload_to='blog_image')),
                ('image8', models.ImageField(upload_to='blog_image')),
                ('image9', models.ImageField(upload_to='blog_image')),
                ('image10', models.ImageField(upload_to='blog_image')),
                ('image11', models.ImageField(upload_to='blog_image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
