# Generated by Django 4.0.4 on 2022-06-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0005_city_mountain_alter_island_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mountain',
            new_name='city_pic',
        ),
        migrations.RenameModel(
            old_name='city',
            new_name='mountain_PIC',
        ),
    ]
