# Generated by Django 4.0.4 on 2022-07-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0007_event_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city_pic',
        ),
        migrations.DeleteModel(
            name='Island',
        ),
        migrations.DeleteModel(
            name='mountain_PIC',
        ),
    ]
