# Generated by Django 4.0.4 on 2022-07-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0008_delete_city_pic_delete_island_delete_mountain_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog_image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
