# Generated by Django 4.0.4 on 2022-07-08 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0009_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='projects',
            name='image10',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image11',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image6',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image7',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image8',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image9',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
