# Generated by Django 4.0.4 on 2022-07-19 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0010_rename_image_projects_image1_projects_image10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_page_pic',
            name='image12',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_pic',
            name='image13',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_pic',
            name='image14',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_pic',
            name='image15',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_pic',
            name='image16',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_pic',
            name='image17',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_pic',
            name='image18',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_pic',
            name='image19',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
