# Generated by Django 4.0.4 on 2022-07-19 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0011_main_page_pic_image12_main_page_pic_image13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potraits',
            name='image12',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potraits',
            name='image13',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potraits',
            name='image14',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potraits',
            name='image15',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potraits',
            name='image16',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potraits',
            name='image17',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potraits',
            name='image18',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potraits',
            name='image19',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
