# Generated by Django 4.0.4 on 2022-07-19 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0012_potraits_image12_potraits_image13_potraits_image14_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_pic',
            name='image12',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_pic',
            name='image13',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_pic',
            name='image14',
            field=models.ImageField(default=1, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_pic',
            name='image15',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_pic',
            name='image16',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_pic',
            name='image17',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_pic',
            name='image18',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_pic',
            name='image19',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image12',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image13',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image14',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image15',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image16',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image17',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image18',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image19',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
