# Generated by Django 4.0.4 on 2022-07-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0013_event_pic_image12_event_pic_image13_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image9',
        ),
    ]
