# Generated by Django 4.0.4 on 2022-07-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0014_rename_image1_projects_image_remove_projects_image10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog_image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image10',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image11',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image12',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image13',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image14',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image15',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image16',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image17',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image18',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image19',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image6',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image7',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image8',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='image9',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
