# Generated by Django 4.0.4 on 2022-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0015_booking_remove_projects_image_projects_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='droneshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
            ],
        ),
    ]
