# Generated by Django 4.0.4 on 2022-07-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0018_event_pic_image20_event_pic_image21_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='potraits',
            new_name='potrait',
        ),
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
