# Generated by Django 4.0.4 on 2022-07-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0019_rename_potraits_potrait_rename_projects_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='project_pic',
        ),
    ]
