# Generated by Django 4.0.4 on 2022-07-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamiapp', '0020_rename_project_project_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='potrait',
            new_name='potrait_pic',
        ),
        migrations.RenameModel(
            old_name='project_pic',
            new_name='project',
        ),
    ]
